services:
  ui:
    build:
      context: ../
      target: dev
    env_file:
      - ../.env
    volumes:
      - ../:/workspace
    command: sleep infinity
  # postgres:
  #   image: postgres:17
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
# volumes:
#   postgres:
